# Generated by Django 5.0.1 on 2024-07-08 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentsconnect', '0003_alter_category_slug_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='follows',
            field=models.ManyToManyField(blank=True, related_name='followed_by', to='studentsconnect.userprofile'),
        ),
    ]
