# Generated by Django 5.0.1 on 2024-07-10 17:22

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentsconnect', '0005_userprofile_date_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='country',
            field=django_countries.fields.CountryField(default='', max_length=2),
            preserve_default=False,
        ),
    ]
