# Generated by Django 5.0.1 on 2024-07-11 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentsconnect', '0006_userprofile_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_bio',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
