# Generated by Django 5.0.1 on 2024-07-23 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentsconnect', '0010_country_alter_userprofile_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='picture',
            field=models.ImageField(blank=True, upload_to='category_images'),
        ),
    ]
