# Generated by Django 5.0.1 on 2024-07-25 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentsconnect', '0012_university_userprofile_university'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='picture',
            field=models.ImageField(blank=True, upload_to='page_images'),
        ),
    ]
